name: Mythril

on: [push, pull_request]

jobs:
  fmt:
    runs-on: ubuntu-18.04
    container:
      image: adamschwalm/hypervisor-build:16
      options: "-u 0:0"
    steps:
    - uses: actions/checkout@v1
    - name: Format
      run: |
        make check-fmt
  test:
    runs-on: ubuntu-18.04
    needs: fmt
    container:
      image: adamschwalm/hypervisor-build:16
      options: "-u 0:0"
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: true
    - name: Unit Tests
      run: |
        make test
  build:
    runs-on: ubuntu-18.04
    needs: fmt
    container:
      image: adamschwalm/hypervisor-build:16
      options: "-u 0:0"
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: true
    - name: Multiboot2 Image Build
      run: |
        RUSTFLAGS="-D warnings" make mythril
